version: '3'

services:

        mysql:
                build: ./mysql
                ports:
                        - 3306:3306
                environment:
                        MYSQL_ROOT_PASSWORD: example
                volumes:
                        - database-location:/var/lib/mysql
                networks:
                        - data

        flask:
                build: ./flask
                ports:
                        - 9090:9090
                volumes:
                        - static-content:/static
                networks:
                        - data
                        - front
                depends_on:
                        - mysql
        
        nginx:
                build: ./nginx
                ports:
                        - 80:80
                        - 443:443
                volumes:
                        # - nginx-conf:/etc/nginx
                        - ssl-certificates:/etc/nginx/ssl
                        - static-content:/sites/club/static  
                networks:
                        - front
                depends_on:
                        - flask
        cron:
                build: ./cron
                volumes:
                        - ssl-certificates:/ssl-certificates
                networks:
                        - private
                depends_on:
                        - nginx

volumes:
        # nginx-conf:
        ssl-certificates:
        static-content:        
        database-location:
networks:
        front:
                driver: bridge
        data:
                driver: bridge
        private:
                driver: bridge



